### ISSUE TITLE
7z doesn't work

### ISSUE THREAD

**Issue by gen2brain** [MStoykov/go-libarchive#1]
# ./example ../fixtures/test.7z 
    file  ../fixtures/test.7z
    Name a
    panic: runtime error: slice bounds out of range

    goroutine 1 [running]:
    bytes.(*Buffer).ReadFrom(0xc820053e58, 0x7fa8aea9c240, 0xc8200104b0, 0x0, 0x0, 0x0)
        /home/milann/go/src/bytes/buffer.go:174 +0x322
    main.printContents(0x7fff96f26d0c, 0x13)
        /home/milann/golang/src/github.com/MStoykov/go-libarchive/example/main.go:32 +0x713
    main.main()
        /home/milann/golang/src/github.com/MStoykov/go-libarchive/example/main.go:45 +0xb1

    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
        /home/milann/go/src/runtime/asm_amd64.s:1805 +0x1

    # ./example ../fixtures/test2.7z 
    file  ../fixtures/test2.7z
    Error on reader.Next():
    libarchive: FATAL [critical error, archive closing]

    # ldd ./example | grep lzma
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f9e03dc5000)

**Comment by MStoykov** [comment]
After 4477d8e I don't get the panic but I always get `libarchive: FATAL [critical error, archive closing]`. 
Maybe this is a bug in libarchive ?
Could you try to write a C program that works with 7z, this will probably shine some light on what is wrong.

**Comment by gen2brain** [comment]
I wrote a test in C https://gist.github.com/gen2brain/c6745855028de8341175 . When "archive_read_open_filename" is used it works, but "archive_read_open"  next header returns error -30.

I think the problem is  that for archive_read_open to read 7z and some zip files, seek callback needs to be provided ( https://github.com/libarchive/libarchive/issues/437 , https://github.com/libarchive/libarchive/wiki/LibarchiveIO ) . 

I found example implementetion in C++ here https://github.com/evilrix/catfood/tree/libarchive-issues-535 .
